name: CI

on:
  push:
    branches:
      - 'main'
      - 'next'
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}
    steps:
      - name: Init
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      # - name: Dependencies
        # uses: bahmutov/npm-install@v1
      - name: Setup .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN}} " > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
      - name: Sync Checks
        run: |
          npx @checkly/cli@canary conf apiKey ${{ secrets.CHECKLY_API_KEY }}
          npx @checkly/cli@canary checks deploy
        env:
          CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}
