name: CI

on:
  push:
    branches:
      - 'main'
      - 'next'
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Init
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      # - name: Dependencies
        # uses: bahmutov/npm-install@v1
      - name: Run tests
        run: npx @checkly/cli@canary checks deploy
